### ISSUE TITLE
Email Student Notifications on SectionEvent creation

### ISSUE THREAD

**Issue by seveibar** [rcos/venue#100]

**Comment by kmcnellis** [comment]
depends on https://github.com/rcos/venue/issues/281

**Comment by seveibar** [comment]
Joey, please do the scheduler in a separate PR if possible (unless it's small)

**Comment by kmcnellis** [comment]
Maybe this should be a summary of all the events added in the past day?

**Comment by seveibar** [comment]
@leej42 is this implemented?

**Comment by jowlee** [comment]
Should be good after pull request #384 . 
Would love it if someone could also test it out.

**Comment by seveibar** [comment]
#384 is merged, i'll be doing tests tonight and will reopen if something doesn't work
