### ISSUE TITLE
All GET parameters should accept "me" instead of id when doing user query

### ISSUE THREAD

**Issue by seveibar** [rcos/venue#138]
For example, `withStudent` should be able to accept an id OR "me". 

To do this a utility function should be built that takes a url input and request and turns it into a proper mongoose object id

**Comment by jowlee** [comment]
This should be in a testing suite or fixed on a per endpoint basis

**Comment by seveibar** [comment]
as of #353 it is in the test suite and it is largely done by most endpoints
