### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by seveibar** [rcos/venue#146]
Admin panel needs to be started

**Comment by samanthajlee2** [comment]
Add and remove users - should be in the CSV thing

todo here:
[ ] split users into admins, instructors, students
[ ] sort users alphabetically
[ ] default to Admin tab

**Comment by seveibar** [comment]
default to Admin tab?

**Comment by samanthajlee2** [comment]
yep default to admin panel.

**Comment by seveibar** [comment]
haha sam what does that mean? The default page for an admin?

**Comment by samanthajlee2** [comment]
you know how there's a dashboard page? right now when you log in as admin, it brings you to the dashboard. I think we should have the first page they see be the admin page. so this view:
![jul03_172639](https://cloud.githubusercontent.com/assets/7064046/16547668/549a483e-4143-11e6-9848-5f0ef0de3e21.png)
