### ISSUE TITLE
Instructor Page: Add course links

### ISSUE THREAD

**Issue by samanthajlee2** [rcos/venue#166]
add links from dashboard and courses page
(to where the search courses link goes to)

**Comment by samanthajlee2** [comment]
good for dashboard, can you do the same for the courses page? Or is there not supposed to be a courses page for the instructor?...
![mar05_124459](https://cloud.githubusercontent.com/assets/7064046/13549290/4acdb3e4-e2d0-11e5-89ee-41b1b14cb7c8.png)

**Comment by jowlee** [comment]
I made a new issue for it #180
