### ISSUE TITLE
Instructor page: menu change

### ISSUE THREAD

**Issue by samanthajlee2** [rcos/venue#170]
what do you guys think about adding a student submissions item? between Dashboard and Create Event?

I think those are the 2 primary things profs will do: create events and check student submissions.

**Comment by kmcnellis** [comment]
This is already done?

**Comment by samanthajlee2** [comment]
The thought here was to change the menu at the top
![apr29_130708](https://cloud.githubusercontent.com/assets/7064046/14923452/59cd8b6a-0e0b-11e6-9131-9f45da9a8b50.png)

If we think it's unnecessary that's okay too.

**Comment by kmcnellis** [comment]
I think it would clutter up the menubar more

**Comment by samanthajlee2** [comment]
hmm alright, I'm in agreement here.
