### ISSUE TITLE
Instructor should be able to see all students in a course

### ISSUE THREAD

**Issue by seveibar** [rcos/venue#172]

**Comment by kmcnellis** [comment]
We should have a course page that the instructor can view all the info in, rather than a page just for viewing students.

**Comment by samanthajlee2** [comment]
@kmcnellis I think you're right about that. As an instructor, currently there is this course page, but there should be more info, like viewing the students. Do you think it's appropriate to add that info to this page?

![mar06_221307](https://cloud.githubusercontent.com/assets/7064046/13560027/a9688b22-e3e8-11e5-8758-14435f4061f6.png)

**Comment by kmcnellis** [comment]
Thats what I thought to do as well

**Comment by kmcnellis** [comment]
Sorry, that is not implemented at all yet. It was just a wireframe

**Comment by samanthajlee2** [comment]
That's fine, just wanted to document it
