### ISSUE TITLE
Need SectionEvent API Endpoints and Documentation

### ISSUE THREAD

**Issue by jboulter11** [rcos/venue#178]
Please update API.md to reflect the endpoints for SectionEvents.  I specifically need to get sectionEvents for a course by specifying courseId.

EDIT

I'd also like to know if a user has already submitted to a SectionEvent as an endpoint.

**Comment by kmcnellis** [comment]
There would be no sectionEvents for a course, just for a section.  The behavior will be that if `onlySection=:sectionId` is specified, then the sectionEvents for that section will be returned.

The second part of the request will be through the submissions api, using `onlyNumber=true` along with the other parameters to filter down the request (they are already documented), and it will return a count of the previous submissions (this includes someone submitting on your behalf)
