### ISSUE TITLE
GET SectionEvent for both User and SectionEvent

### ISSUE THREAD

**Issue by jboulter11** [rcos/venue#179]
I need an endpoint for knowing if a user has submitted attendance to a SectionEvent already.

Basically I need GET /api/submissions?onlyStudent=me?onlySectionEvent=:eventId to be a thing, but it currently gives me a 500.

**Comment by kmcnellis** [comment]
It should be GET /api/submissions?onlyStudent=me**&**onlySectionEvent=:eventId, but that is probably not the main issue
