### ISSUE TITLE
(Student) Sign up: Error messages

### ISSUE THREAD

**Issue by samanthajlee2** [rcos/venue#183]
Add error messages for first and last name

![mar06_222408](https://cloud.githubusercontent.com/assets/7064046/13560172/454bc24c-e3ea-11e5-8ca5-741f0eadbbd9.png)

**Comment by samanthajlee2** [comment]
please add a space...
![mar22_232449](https://cloud.githubusercontent.com/assets/7064046/13974792/4e6eb832-f085-11e5-8b5c-d0dbb8650a65.png)

**Comment by jowlee** [comment]
Nice catch. Should be good now.
