### ISSUE TITLE
log out on a specific course

### ISSUE THREAD

**Issue by samanthajlee2** [rcos/venue#188]
instructor & user both see the following after log out on for a specific course. To be consistent with current log out for other pages, we should return the user to the login page.

![mar16_160550](https://cloud.githubusercontent.com/assets/7064046/13827049/fd50e9aa-eb90-11e5-9fcc-0d701a47c499.png)

**Comment by samanthajlee2** [comment]
something to consider: since non-logged in users can see specific courses, maybe logging out should just remove the option in enroll.
![mar16_160954](https://cloud.githubusercontent.com/assets/7064046/13827207/a5423308-eb91-11e5-8d39-85770980cd9f.png)
![mar16_161008](https://cloud.githubusercontent.com/assets/7064046/13827208/a54b1202-eb91-11e5-9d84-c15425af3e2a.png)

**Comment by kmcnellis** [comment]
This is an odd bug... it seems that the url is being changed to http://localhost:9000/courses/:id after logout.  So the 2 issues that need to be fixed is rejecting incorrect ids and redirecting to the correct page on logout. 

I'm curious if anyone has found this happening on other pages?
