### ISSUE TITLE
Images for Courses or Sections, whichever makes sense

### ISSUE THREAD

**Issue by jboulter11** [rcos/venue#214]
In order to match the app's designs there needs to be images for the courses or sections a student is a part of.  Pull these from some CC source for maximum artsy feel.

If we're not going to have images here (and I'd highly recommend we do) then let's discuss.

**Comment by jboulter11** [comment]
This needs to happen still.

**Comment by kmcnellis** [comment]
Added, just need to integrate a instructor selection of images
