### ISSUE TITLE
Student Upload: Fix links

### ISSUE THREAD

**Issue by samanthajlee2** [rcos/venue#228]
On the student upload page, when selecting an event, if there are multiple options, all link to the first option.

For example:
clicking on the ARTS 1020 | sections: 1,2,3,4
![may03_234614](https://cloud.githubusercontent.com/assets/7064046/15004804/8276f408-1189-11e6-8d15-4d1434c51059.png)
shows
![may03_234954](https://cloud.githubusercontent.com/assets/7064046/15004820/c272cd66-1189-11e6-93d0-d85a6e6f4eeb.png)

**Comment by jowlee** [comment]
Should be fixed!
