### ISSUE TITLE
Enrollment Policy

### ISSUE THREAD

**Issue by samanthajlee2** [rcos/venue#245]

**Comment by kmcnellis** [comment]
More elaboration?

**Comment by samanthajlee2** [comment]
it seems to me that [ closed / open / approval required ] all does the same thing (which is open). This needs to either be eliminated or made to match what it's supposed to do.

**Comment by seveibar** [comment]
I'm going to remove the closed option for now b/c we don't support it. We do support approval required so I'll see what we can do there.

**Comment by samanthajlee2** [comment]
Sounds good.
