### ISSUE TITLE
Dedicated Event Search Page

### ISSUE THREAD

**Issue by seveibar** [rcos/venue#305]
An instructor should have a tab at the top of the page that is similar to the course page that allows them to search for events that they've assigned (they can then click this to get submissions via #304 )

**Comment by jowlee** [comment]
@seveibar @samanthajlee2 Should this only be page for instructors, or will it be open like the course search page and tailored for instr, students, and public view. Should it have a filter to be organized by date/courses/assigned/(Category possibly?)

**Comment by seveibar** [comment]
I think this should be open and should have filters as you suggested for instructors, students etc. I don't think the filters are necessarily necessary for the initial commit but are important in the long run.

This should also be a tab at the top similar to search courses

**Comment by samanthajlee2** [comment]
@leej42 I like what @seveibar said - could also have two pages - one for upcoming events, one for past events
