### ISSUE TITLE
GPS and grading should work fully

### ISSUE THREAD

**Issue by kmcnellis** [rcos/venue#382]
I'd like suggestions on what this should look like to students and professors

**Comment by seveibar** [comment]
Grading is not necessary- if you download an instructors CSV from a page with a submission view (or just look at the view) you can see there's a "valid" column. I put that on premptively under the assumption we would have a "valid" property in each submission indicating if the correct location was submitted. I think all we need to do is add that property with GPS validation and we're done

**Comment by seveibar** [comment]
GPS is now working, going to close

**Comment by seveibar** [comment]
please open if there are other concerns tho
