### ISSUE TITLE
Internal Server Error when logging out as a student from /eventinfos and /events pages

### ISSUE THREAD

**Issue by charlieyou** [rcos/venue#426]
`{"data":{"message":"Cast to ObjectId failed for value \":id\" at path \"_id\" for model \"EventInfo\"","name":"CastError","stringValue":"\":id\"","kind":"ObjectId","value":":id","path":"_id"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/api/eventinfos/:id","params":{"withAuthor":true,"withSectionEvents":true,"withCourses":true},"headers":{"Accept":"application/json, text/plain, */*","X-XSRF-TOKEN":"NAWhfVmCA0af3AgRVt4TGDjvmubndB+zadfcw="}},"statusText":"Internal Server Error"}`

**Comment by vakrao** [comment]
Also getting 500 error when logging out of courses; but site does not show it. I think there is a general issue with how logout is done here
