### ISSUE TITLE
Add visual to show user is logged in on front page

### ISSUE THREAD

**Issue by kmcnellis** [rcos/venue#431]

**Comment by vakrao** [comment]
Should this be handled in a similar way to how github handles this; where if a user is logged in they are redirected to their dashboard?

**Comment by tayloa** [comment]
The splash page probably should just redirect or not be shown if the user is logged in.

**Comment by vakrao** [comment]
Can you make a new PR that just fixes this issue without adding any CSV changes @tayloa ?
